### ISSUE TITLE
fastNaiveBayes.multinomial does not work with dgCMatrix

### ISSUE THREAD

**Issue by jwijffels** [mskogholt/fastNaiveBayes#2]
I'm getting unexpected results with an object of class dgCMatrix passed on to fastNaiveBayes.multinomial
Documentation says it accepts this but it does not, it apparently only handles data.frames correctly. Example

```
library(udpipe)
library(fastNaiveBayes)
data(brussels_reviews, package = "udpipe")
data(brussels_listings, package = "udpipe")
X <- document_term_frequencies(brussels_reviews, document = "id", term = "feedback")
X <- document_term_matrix(X)
class(X)
[1] "dgCMatrix"
attr(,"package")
[1] "Matrix"
Y <- brussels_listings$room_type[match(rownames(X), brussels_listings$listing_id)]

model <- fastNaiveBayes.multinomial(x = X, y = Y)
Error in base::rowSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions
```

**Comment by martinskogholt** [comment]
Hmm, this is weird, I even put up unit tests to test this bevahior. Thank you for the nice example I will check this weekend what's going on. In the meantime does it work if you set sparse = TRUE as a parameter?

**Comment by jwijffels** [comment]
No it is not. Error is coming from here: https://github.com/mskogholt/fastNaiveBayes/blob/master/R/fastNaiveBayes.multinomial.default.R#L27 and you always overwrite internally in your code sparse=TRUE when you pass on a dgCMatrix https://github.com/mskogholt/fastNaiveBayes/blob/master/R/fastNaiveBayes.multinomial.default.R#L13

**Comment by jwijffels** [comment]
My apologies, it was working. Made an error on myside. Correct code was.

```
library(udpipe)
library(fastNaiveBayes)
data(brussels_reviews, package = "udpipe")
data(brussels_listings, package = "udpipe")
X <- document_term_frequencies(brussels_reviews, document = "listing_id", term = "feedback")
X <- document_term_matrix(X)
Y <- brussels_listings$room_type[match(rownames(X), brussels_listings$listing_id)]
Y <- factor(Y)
model <- fastNaiveBayes.multinomial(x = X, y = Y)
```

**Comment by mskogholt** [comment]
Ah okay good, or at least good that it was not the package itself. Thank you very much for the feedback and for checking. I really appreciate any user feedback to make this implementation better!
