### ISSUE TITLE
Is it an error for fastNaiveBayes?

### ISSUE THREAD

**Issue by newuserof1017e** [mskogholt/fastNaiveBayes#6]
I tried your code and get an error
>  dist <- fastNaiveBayes::fastNaiveBayes.detect_distribution(x, nrows = nrow(x))

 'fastNaiveBayes.detect_distribution' is not an exported object from 'namespace:fastNaiveBayes'

**Comment by martinskogholt** [comment]
Ah I think my examples are outdated. In version 2.1.0 the naming structure was changed. If you use: fnb.detect_distribution it should be fine. Where did you find that piece of code?

**Comment by newuserof1017e** [comment]
I just google "Fast Naive Bayes r" and click the first link:
https://cran.r-project.org/web/packages/fastNaiveBayes/vignettes/fastnaivebayes.html 
The date is new (2019-08-27), so I read the webpage and run the example. 
I just click the second link and get the right example. 
https://cran.r-project.org/web/packages/fastNaiveBayes/index.html
Many thanks.
